F.addLog("mancard:skeleton/card",{scrollLoad:"4010311000"});F.module("mancard:skeleton/card",function(require,exports,ctx){var OneCard=function(){var _cssReg=/<link[^>]*href="(.*?)"[^>]*>/;var _menuDom=$("#s_menus_wrapper");var _centerMen=$("#s_ctner_menus");var _isPull="";function OneCard(id,name,state){this.id=""+id||"";this.loaded=0;this.offsetUsed=false;this.html="";this.name=name||"";this.state=state||"";this.mainDom=$("#s_content_"+this.id)
;this.mainDom=this.mainDom[0]?this.mainDom:_cardMaker({id:this.id});this.waterDom=null;this.noMore=false;this.myMen=null;this.rendered=false;this.waterPage=0;this.waterLoading=false;this.cutnetTimes=0;this.prevRidsArr=window.s_session.rids||[];this.repeatNum=0;this.ridsHash={};this.params={};this.forceLoad=false}OneCard.prototype={constructor:OneCard,load:function(cb){var _ctx=this;if(_ctx.id!=""){if(_ctx.loaded===0||_ctx.forceLoad){_ctx.loaded=1;_ctx.params.id=_ctx.id;_loadCardHtml(_ctx.params,
function(data){_ctx.loaded=2;_ctx.sessionId=data.sessionId;_ctx.prevRidsArr=data.rids;for(var i=0,dataRids=data.rids||[],l=dataRids.length;i<l;i++){_ctx.ridsHash[dataRids[i]]=true}_ctx.html=data.html.replace(_cssReg,"");if(data.isEnd==1){_ctx.noMore=true}_ctx.loadCss(data.html,cb)})}}},loadCss:function(html,cb){var match,href;if(html){match=html.match(_cssReg);if(match){href=match[1];$('<link rel="stylesheet" type="text/css" href="'+href+'" />').on("load",function(){cb&&cb(html)}).appendTo(head)
;if($.browser.safari&&window.navigator.platform==="Win32"){cb&&cb(html)}}else{cb&&cb(html)}}else{ctx.fire("syncNomore",{cardId:this.id})}},appendData:function(cb,toggle,$dom){var _ctx=this;if(_ctx.noMore||_ctx.waterLoading||!_ctx.rendered){if(_ctx.noMore){toggle&&toggle(false)}return false}if(!_ctx.loadDom){_ctx.loadDom=_ctx.mainDom.find(".s-loading")}_ctx.waterLoading=true;toggle&&toggle(false);var params={id:_ctx.id,offset:_ctx.waterPage,sessionId:_ctx.sessionId,crids:window.s_session.crids}
;var paraDom=_ctx.mainDom||$("#s_content_"+_ctx.id);var extraParam=paraDom.attr("data-waterpara");if(!extraParam&&paraDom.find(".s-xmancard").attr("data-waterpara")){extraParam=paraDom.find(".s-xmancard").attr("data-waterpara")}if(extraParam){var regx=/([s\S]*?)\=([\s\S]*?)\;/g;var result=null;while(result=regx.exec(extraParam)){if(result[1]==="offset"){if(!_ctx.offsetUsed){params[result[1]]=result[2];_ctx.waterPage=result[2];_ctx.offsetUsed=true}}else{params[result[1]]=result[2]}}}
params.newsNum=params.newsNum||params.pos;params.needAd=1;params.refresh_state=-1;ctx.fire("beforeLoading");_ctx.loadDom.show();ctx.fire("scrollLoad");F.use("mancard:skeleton/model",function(dao){dao.get("waterHtml",function(data){if(data.autoRefresh){_ctx.waterLoading=false;return}if(!_ctx.waterDom){_ctx.waterDom=$(".water-container",_ctx.mainDom)}if(params.childId==="1_1"&&params.sessionId==="0"){_ctx.ridsHash={}}var repeat=_ctx.validateRid(data);var waterFunc=[function(){
var target=$dom||_ctx.waterDom;var $html=$(data.html);var htmlId="waterpage"+_ctx.waterPage;$html.attr("id",htmlId);target.append($html);_ctx.waterLoading=false;_ctx.loadDom.hide();if(data.isEnd=="1"){_ctx.emitNoMore(_ctx.loadDom);_ctx.noMore=true}_ctx.waterPage++;_ctx.mainDom.attr("data-loaded",1);if(typeof F==="object"){try{F.call("superman:components/initSan","init","#"+htmlId)}catch(e){console.error(e)}}if(_ctx.id===2&&data.isEnd==="0"){_ctx.mainDom.find("div[data-waterpara]").attr(
"data-waterpara","version="+data.version+";"+data.waterpara)}ctx.fire("cardloaded",{cardId:_ctx.id,loadData:data});cb&&cb.call(_ctx,data)},function(){setTimeout(function(){_ctx.waterLoading=false;_ctx.appendData(cb,toggle)},50)},function(){setTimeout(function(){_ctx.waterLoading=false;_ctx.appendData(cb,toggle)},50)},function(){setTimeout(function(){_ctx.waterLoading=false;_ctx.appendData(cb,toggle)},50)},function(){$.ajaxpost(s_domain.baseuri+"/page/data/pageserver",{errno:7009})
;_ctx.emitNoMore(_ctx.loadDom);_ctx.noMore=true}];_isPull=_isPull===""||_isPull==1?"1":undefined;_ctx.cutnetTimes=0;waterFunc[repeat]()},params).fail(function(){$.ajaxpost(s_domain.baseuri+"/page/data/pageserver",{errno:8001});_ctx.cutnetTimes++;if(_ctx.cutnetTimes<=3){_ctx.waterLoading=false;_ctx.appendData(cb,toggle)}else{_ctx.emitNoMore(_ctx.mainDom.find(".s-loading"))}})});return true},validateRid:function(data){var _ctx=this;var nextArr=data.rids||[];var isRepeat=0;var len=nextArr.length
;for(var i=0;i<len;i++){if(!!nextArr[i]&&!!_ctx.ridsHash[nextArr[i]]){isRepeat=1}}if(isRepeat===1){_ctx.repeatNum++}else if(_ctx.repeatNum>0){_ctx.repeatNum=0}if(isRepeat===0){for(i=0;i<len;i++){_ctx.ridsHash[nextArr[i]]=true}}_ctx.prevRidsArr=nextArr;return _ctx.repeatNum},render:function(cb){var _ctx=this;$("#s_ctner_contents").append(this.mainDom);_ctx.load(function(html){var $curDom=$(_ctx.html);_ctx.mainDom.html($curDom);if(_ctx.noMore){_ctx.emitNoMore(_ctx.mainDom.find(".s-loading"))}
_ctx.rendered=true;cb&&cb();var bds=window.bds;var sampleval=bds&&bds.comm&&bds.comm.desktopSampleval;if(sampleval){var _html=_ctx.html;var isNode=/s_xmancard_desktop/.test(_html);if(+_ctx.id===100){if(!isNode){$(window).trigger("desktopNotNode")}else{$(window).trigger("desktopNode")}}}ctx.fire("cardinitloaded")});return _ctx},add2Men:function(cb){var _ctx=this;if(!_ctx.myMen){var tpl=_menuMaker({id:this.id,name:this.name});_ctx.myMen=$(tpl)}if(this.id==="3"){_menuDom.parent().append(_ctx.myMen)
;F.call("newmusic:index","init")}else{_menuDom.append(_ctx.myMen)}_ctx.myMen.show();_ctx.render();return _ctx},del4Men:function(cb){var _ctx=this;if((_ctx.myMen=$("[data-id="+this.id+"]",_menuDom))[0]){_ctx.myMen.hide();_ctx.mainDom.hide();_ctx.state=""}return _ctx},show:function(cb){var _ctx=this;if(this.rendered){if(_isPull==1&&this.waterPage==0){this.appendData(function(data){})}this.mainDom.stop().show()}else{this.render(function(){cb&&cb.call(this)});this.mainDom.stop().show()}cb&&cb.call(
this);this.getMyMen().addClass("current");return this},hide:function(cb){this.mainDom.stop().hide();this.getMyMen().removeClass("current");cb&&cb.call(this);return this},getMyMen:function(){return this.myMen||(this.myMen=$("[data-id="+this.id+"]",_centerMen))},emitNoMore:function($dom){$dom=$dom||this.mainDom.find(".s-loading");$dom.find(".load-text").addClass("no-more").html("没有更多内容了").end().find("img").hide().end().prepend('<div class="load-done"></div>').show();if(
this.id==100||this.id=="1"||this.id=="22"||this.id==24){$dom.hide()}ctx.fire("cardLoadDone",{cardId:this.id})},resetNoMore:function($dom){$dom=$dom||this.mainDom.find(".s-loading");$dom.hide().find(".load-text").removeClass("no-more").html("正在加载中").end().find("img").show().end().find(".load-done").remove()},setForceLoad:function(force){this.forceLoad=force},addParam:function(name,value){this.params[name]=value}};function _menuMaker(set){var tpl;if(set.id==="3"){
tpl='<div class="s-menu-music" data-id="#{id}"></div>'}else if(set.id==="5"){tpl=['<span class="s-menu-item s-opacity-white-background" data-id="#{id}">',"<span>#{name}</span>",'<span class="bar-bg" data-tid="7779"></span>',"</span>"].join("")}else if(set.id==="24"){tpl=['<span class="s-menu-item s-opacity-white-background" data-id="#{id}">',"<span>#{name}</span>",'<span class="bar-bg" data-tid="7999"></span>',"</span>"].join("")}else{tpl=[
'<span class="s-menu-item s-opacity-white-background" data-id="#{id}">',"#{name}","</span>"].join("")}return $.formatString(tpl,set)}function _cardMaker(set){var loading=s_domain.staticUrl+"static/mancard/img/loading-f9b765014b.gif";if(window.isNewGridCard===1){loading=s_domain.staticUrl+"static/mancard/img/loading_new-f4a658cef0.gif"}var tpl=""+'<div id="s_content_#{id}" data-id="#{id}" class="s-content" style="display:none;">'+'<div class="s-content-load '+(
window.isNewGridCard===1?"":"s-opacity-white-background")+'">'+'<img src="#{loadingImg}" />'+(window.isNewGridCard===1?"":"<div>加载中，精彩马上呈现</div>")+"</div>"+"</div>";$.extend(set,{staticUrl:s_domain.staticUrl,loadingImg:loading});return $($.formatString(tpl,set))}function _loadCardHtml(params,cb){if(params.id==="5"&&!params.childId){params.childId="0"}params.isPull=_isPull||"";F.use("mancard:skeleton/model",function(dao){dao.get("cardHtml",function(data){cb&&cb(data)},params)})}return OneCard}()
;return OneCard});
F.module("mancard:skeleton/model",function(require,exports,tool){var _uri="/home/pcweb/";var _uri_mancardwater=window.is_login===0?"/home/page/":_uri;var autoRefreshLoading=false;function Dao(){}var _getter={waterHtml:function(cb,param){var _id=param.id||0,page=param.page||1;var defer=$.Deferred();if(autoRefreshLoading){cb({autoRefresh:true});defer.resolve();return defer}if(+param.refresh_state===4){autoRefreshLoading=true}if(param.id==="1"&&!s_session.isLogin){cb({html:$(
"#s_content_2_more_textarea").text(),sessionId:"",isEnd:true});defer.resolve();autoRefreshLoading=false;return defer}if(+param.noload===1){cb&&cb({html:""});autoRefreshLoading=false;defer.resolve()}else{return $.ajaxget(_uri_mancardwater+"data/mancardwater?"+$.param(param),function(data){autoRefreshLoading=false;cb&&cb(data)})}return defer},cardHtml:function(cb,param){if(param.id==="1"&&!s_session.isLogin){cb({html:$("#s_content_2_textarea").text(),sessionId:""});return}var getStr=$.param(param)
;$.ajaxget(_uri_mancardwater+"data/mancardhtml?"+getStr,function(data){cb&&cb(data)})}};var _setter={curmenu:function(value,cb,param){var id=value||0;$.ajaxpost(_uri+"submit/mancardmenu",{id:value},function(data){cb&&cb(data)})}};Dao.prototype={get:function(key,cb,param){return _getter[key]&&_getter[key](cb,param)||false},set:function(key,value,cb,param){return _setter[key]&&_setter[key](value,cb,param)||false}};return new Dao});
F.module("mancard:skeleton/card_collection",function(require,exports,ctx){var OneCard=require("mancard:skeleton/card");var _menuGurd=$("#s_menu_gurd");var _topWrap=$("#s_top_wrap");var _container=$("#s_mancard_main .s-menu-container");function CardCollection(){this.pool={};this.curId=s_session.curmod;this._options={};this.menuTopShowed=false}CardCollection.prototype={constructor:CardCollection,add:function(aCard,name,state){if(aCard instanceof OneCard){return this.pool[aCard.id]=aCard}else if(
typeof parseInt(aCard)=="number"&&name!=null&&state!=null){return this.pool[""+aCard]=new OneCard(aCard,name,state)}return aCard},remove:function(aCard){if(aCard instanceof OneCard){this.pool[aCard.id]=null}else if(typeof parseInt(aCard)=="number"){this.pool[""+aCard]=null}return aCard},get:function(id){return this.pool[""+id]},createCard:function(id,name,state){if(this.pool[id]){return this.pool[""+id]}return new OneCard(id,name,state)},switchCard:function(id,cb){var _ctx=this;if($(
"#s_top_wrap").hasClass("s-down")){if(_ctx.pool[""+id].waterPage==0){if($.isIE<9){_ctx.fixIE(0,function(){})}else{window.scrollTo($(window).scrollLeft(),0)}}else{var sTop=Math.max($("#s_ctner_contents").offset().top-110,0);_ctx.fixIE(sTop,function(){})}}_ctx.cardDone(id,cb)},cardDone:function(id,cb){var _ctx=this;_ctx.pool[_ctx.curId].hide(function(){window.s_session.curmod=_ctx.curId=""+id;_ctx.pool[""+id].show(function(){F.use("mancard:skeleton/model",function(dao){dao.set("curmenu",_ctx.curId
)});cb&&cb()})})},getMenuIDS:function(){var menuNodes=$("#s_menus_wrapper").find(".s-menu-item"),ids=[];$.each(menuNodes,function(idx,item){ids.push($(item).attr("data-id"))});return ids},dealDeskTop:function(showTopBar,bar){if(showTopBar){bar.addClass("desktop_bar")}else{bar.removeClass("desktop_bar")}},toggleMenu:function(show,noAnimate){var _ctx=this;var _topNavWrap=_topWrap.children(".s-top-nav");if(!!show){_menuGurd.addClass("s-down");this.dealDeskTop(true,_topNavWrap);if($(
"#s_upfunc_menus .s-lite").hasClass("hide-icon")||!$("#bottom_layer .s-bottom-show").css("display")==="none"||!$("#s-user-setting-menu").hasClass("hiding-feed")){_topNavWrap.append(_menuGurd)}if(!_ctx.menuTopShowed){_topNavWrap.css("display","block");_menuGurd.css({marginTop:-1*_menuGurd.height()}).stop().animate({marginTop:"0"},150)}_ctx.menuTopShowed=true}else{this.dealDeskTop(false,_topNavWrap);if(noAnimate){_menuGurd.removeClass("s-down");_container.append(_menuGurd)}else{_menuGurd.css({
marginTop:"0"}).stop().animate({marginTop:-1*_menuGurd.height()},150,function(){_topNavWrap.css("display","none")})}_ctx.menuTopShowed=false}ctx.fire("showTopMenu",{show:show})},options:function(){switch(arguments.length){case 0:return this._options;case 1:return this._options[arguments[0]];case 2:return this._options[arguments[0]]=arguments[1]}},fixIE:function(top,cb){var _ctx=this;$("html,body").animate({scrollTop:top},500,function(){cb&&cb.call(_ctx)})}};return new CardCollection});
F.addLog("mancard:skeleton/card_showLog",["cardItemShow"]);F.module("mancard:skeleton/card_showLog",function(require,exports,ctx){var cards=require("skeleton/card_collection");var alsLog=require("skeleton/card_alsLog");var thunder=window.Thunder.get();var idsMap={};var feedLoadLogMap={firstRefresh:{tid:11557,logInfo:"top_refresh",isLoad:false},pullRefresh:{tid:11558,logInfo:"pull_refresh"},autoRefresh:{tid:11559,logInfo:"auto_refresh"}};var windowHeight=$(window).height();var defaultLog={
logactid:"1100000004"};function itemShowLog(){var curNodeWrap=$("#s_content_"+cards.curId),items=curNodeWrap.find("[data-rid]"),item=null,ids=idsMap[cards.curId]||[];var temp=[],posTemp=[],extras=[],mapObjArr={};var logExtra=[];for(var i=0;i<items.length;i++){item=items.eq(i);var extra=item.attr("data-extra");var rid=item.attr("data-rid");var tlog;var curLog=item.attr("data-log");if(curLog){curLog=curLog.replace(/\;$/g,"")}if($.inArray(rid,ids)!=-1){continue}if(item.offset().top+item.height(
)/2-$(window).scrollTop()<windowHeight){if(item.hasClass("s-nativead-item")){alsLog.sendAlsShowLog({},{da_locate:+item.attr("data-locate"),extra_param:item.attr("data-extra-param")});var cpmRcvUrl=item.attr("data-cpm-rcv-url");if(cpmRcvUrl){imgLog(cpmRcvUrl)}if(item.hasClass("nativead-empty-order")){ids.push(rid);continue}}if(/logactid/g.test(curLog)){if(curLog){splitLog(curLog,mapObjArr)}ids.push(rid);var param={};for(var i in mapObjArr){param[i]=mapObjArr[i].join(",")}ctx.fire("cardItemShow",
param);continue}if($.inArray(rid,ids)==-1){temp.push(rid);var curtemp={rid:rid,extra:extra,flow:2};if(curLog){splitLog(curLog,mapObjArr);splitLogToObj(curLog,curtemp)}posTemp.push(i);ids.push(rid);extras.push(extra);logExtra.push(curtemp)}}}idsMap[cards.curId]=ids;if(temp.length!=0){var param={rids:temp.join(","),pos:posTemp.join(","),extra:extras.join(",")};for(var i in mapObjArr){param[i]=mapObjArr[i].join(",")}var mergedParam=$.extend({},defaultLog,param);ctx.fire("cardItemShow",mergedParam)
;logext_str=$.stringify(logExtra);if(+s_session.curmod===2){thunder.send({cst:1,tid:27,logExtra:logext_str.substr(1,logext_str.length-2)})}}}function imgLog(src){var n="cpm_rcv_url__"+(new Date).getTime();var c=window[n]=new Image;c.onload=c.onerror=function(){window[n]=null};c.src=src;c=null}function splitLog(curLog,mapObjArr){var keyvalue=[];var key="";var value="";var clrChuo="";var paraString=curLog.split(";");for(var j=0;j<paraString.length;j++){keyvalue=paraString[j].split(":")
;key=keyvalue[0];value=keyvalue[1];if(!/-0$/g.test(key)){if(/-1$/g.test(key)){key=key.replace(/-1$/g,"")}if(!mapObjArr[key]){mapObjArr[key]=[]}mapObjArr[key].push(value)}}}function splitLogToObj(curLog,mapObjArr){var keyvalue=[];var key="";var value="";var paraString=curLog.split(";");for(var j=0;j<paraString.length;j++){keyvalue=paraString[j].split(":");key=keyvalue[0];value=keyvalue[1];mapObjArr[key]=value}}function feedLoadLog(type){var thunderInfo=feedLoadLogMap[type];if(!thunderInfo){return
}if(type==="firstRefresh"){if(thunderInfo.isLoad){return}else{thunderInfo.isLoad=true}}thunder.send({ct:2,cst:1,tid:thunderInfo.tid,logFrom:"feed_index",logInfo:thunderInfo.logInfo})}ctx.listen("mancard:skeleton/card","cardloaded",function(data){var id=data.cardId;if(+id===2){feedLoadLog("pullRefresh")}});exports.itemShowLog=itemShowLog;exports.feedLoadLog=feedLoadLog});
F.module("mancard:skeleton/card_alsLog",function(require,exports,ctx){function imgLog(src){var n="imglog__"+(new Date).getTime();var c=window[n]=new Image;c.onload=c.onerror=function(){window[n]=null};c.src=src;c=null}var ALSLOG_TYPE={CLICK:2,SHOW:3};function AlsLog(){this.init()}AlsLog.prototype={constructor:AlsLog,init:function(){this.alsHostHttp="http://als.baidu.com/clog/clog";this.alsHostHttps="https://als.baidu.com/clog/clog";var productId=39;var clientType=0;var baiduId=$.cookie.get(
"BAIDUID");this.alsCommonFields=this.buildAlsParams(productId,clientType,baiduId)},buildAlsParams:function(productId,clientType,baiduId){return{productId:productId,_client_type:clientType,baiduId:baiduId}},sendAls:function(data){var paramList=[];for(var key in data){paramList.push([encodeURIComponent(key),"=",encodeURIComponent(data[key])].join(""))}imgLog(this.alsHostHttps+"?"+paramList.join("&"))},buildAlsLogData:function(logContent,adContent){var ad=encodeURIComponent($.stringify([$.extend({
da_page:"index",da_page_num:1,da_locate:1,origin_time:+new Date},adContent)]));return $.extend({},this.alsCommonFields,logContent,{ad:ad})},sendAlsClickLog:function(logContent,adContent){this.sendAls(this.buildAlsLogData(logContent,$.extend(adContent,{da_type:ALSLOG_TYPE.CLICK})));return this},sendAlsShowLog:function(logContent,adContent){this.sendAls(this.buildAlsLogData(logContent,$.extend(adContent,{da_type:ALSLOG_TYPE.SHOW})));return this}};return new AlsLog});
F.module("mancard:skeleton/presenter",function(require,exports,ctx){var global=window;var cards=require("skeleton/card_collection");var card_showLog=require("skeleton/card_showLog");var _topDom=$("#s_mancard_main");var _centerMen=$("#s_ctner_menus");var _centContent=$("#s_ctner_contents");var _menuContainer=$(".s-menu-container",_topDom);var _loadMap={};var _menuData=$.parseJSON($.trim($("#s_menus_textarea",_topDom).html()));var windowHeight=$(global).height();var isCardWater=true
;var bds=window.bds;var sampleval=bds&&bds.comm&&bds.comm.desktopSampleval;function init(){_initCards();_bindEvent()}var isFeedFirstLoad=true;function getObjXy(obj){var xy=obj.getBoundingClientRect();var top=xy.top-document.documentElement.clientTop+document.documentElement.scrollTop;var bottom=xy.bottom;var left=xy.left-document.documentElement.clientLeft+document.documentElement.scrollLeft;var right=xy.right;var width=xy.width||right-left;var height=xy.height||bottom-top;return{top:top,
right:right,bottom:bottom,left:left,width:width,height:height}}function checkEleInView(ele){var rect=getObjXy(ele);return rect.top>0&&rect.top+rect.height<window.innerHeight}function feedFirstLoad(id,isToggleMore){if(!isFeedFirstLoad){return}isFeedFirstLoad=false;var $bottomBar=$(".s-more-bar");if($bottomBar.length===0){return}if($bottomBar.length>0&&checkEleInView($bottomBar[0])){if(id==="2"){_loadHelper.tolerance=_loadHelper.defaulSub;_loadHelper.judgeFire();_loadHelper.toggleMore(false)}}}
function desktopEvent(){$("#desktop_opt").on("click",function(){$(window).trigger("desktopOptClick")});$(global).on("desktopNotNode",function(){_loadHelper.handleDeskTop({isNode:false})});$(global).on("desktopNode",function(){$("#desktop_opt").on("click",function(){$(window).trigger("desktopOptClick")});_loadHelper.handleDeskTop({isNode:true})});$(global).on("desktopSkinOn",function(){_loadHelper.handleDeskTop({hasSkin:true})});$(global).on("desktopSkinOff",function(){_loadHelper.handleDeskTop({
hasSkin:false})})}var _loadHelper={defaulSub:300,tolerance:isCardWater?0:300,preTop:0,loaded:false,moreBar:_topDom.find(".s-more-bar"),judgeFire:function(){var _ctx=this;if(_ctx.tolerance===0||s_session.index_off){return}cards.get(cards.curId).appendData(function(data){_ctx.loaded=true},_loadHelper.toggleMore)},toggleMore:function(show){if(!show){_loadHelper.moreBar.remove()}else{_loadHelper.moreBar.show()}},handleDeskTop:function(option,clkCtx){var tabId=clkCtx?clkCtx.attr("data-id"
):cards.curId;var isNode=option&&option.isNode;if(isNode===undefined){var _deskEle=$("#s_xmancard_desktop")[0];isNode=!!(_deskEle&&_deskEle.id==="s_xmancard_desktop")&&tabId==="100"}var hasSkin=option&&option.hasSkin;if(hasSkin===undefined){var _isAllSkined=global._isAllSkined;var userIsNewSkined=window.s_session.userIsNewSkined;hasSkin=_isAllSkined!==undefined?_isAllSkined:userIsNewSkined==="on"}global._isAllSkined=hasSkin;if(tabId==="100"){$("#desktop_opt").addClass("desktop-vis");$(
"#s_ctner_contents").addClass("desktop-ctner-contents")}else{$("#desktop_opt").removeClass("desktop-vis");$("#s_ctner_contents").removeClass("desktop-ctner-contents")}},moreUpFy:function(hasSkin,scroll){var _ctx=this;_loadHelper.moreBar.css({visibility:"visible"});if(window.isNewGridCard){return}var fixTop;if(scroll){if(_ctx.moreUp){fixTop=_centContent.offset().top+_centContent.height()-$(global).height()-$(global).scrollTop();_loadHelper.moreBar.css({bottom:Math.min(Math.max(0,fixTop),10)})}}
if($(global).height()<830){if(_ctx.moreUp!==true){_loadHelper.moreBar.addClass("s-more-up").appendTo(_centContent);_ctx.moreUp=true;fixTop=_centContent.offset().top+_centContent.height()-$(global).height()-$(global).scrollTop();_loadHelper.moreBar.css({bottom:Math.min(Math.max(0,fixTop),10)});repeat(true)}}else{if(_ctx.moreUp!==false){_loadHelper.moreBar.removeClass("s-more-up");_centContent.after(_loadHelper.moreBar);if(!_ctx.morePngLoaded){_loadHelper.moreBar.find(".rect")[0].onload=function(
){_loadHelper.moreBar.css({visibility:"visible"})};_ctx.morePngLoaded=true}_ctx.moreUp=false}if(hasSkin===true){_loadHelper.moreBar.find(".rect").attr("src",s_domain.staticUrl+"static/mancard/img/more_white-2eea3778c1.png")}else if(hasSkin===false){_loadHelper.moreBar.find(".rect").attr("src",s_domain.staticUrl+"static/mancard/img/more_black-0efeff6083.png")}}function repeat(turn){_loadHelper.moreBar.find(".animate-arrow").animate({top:turn?18:8},800,"swing",function(){repeat(!turn)})}},
moreDownFy:function(){if($(global).height()>700){var moreBar=_topDom.find(".s-more-bar").addClass("s-more-up").find(".rect").attr("src",s_domain.staticUrl+(global.s_session.userIsNewSkined==="on"?"static/mancard/img/more_white-2eea3778c1.png":"static/mancard/img/more_black-0efeff6083.png")).end();_centContent.after(moreBar)}}};function _initCards(){var _cardData=_menuData.data;var i=_cardData.length;while(i--){var item=_cardData[i];if(item.state==="1"){cards.add(item.id,item.name,item.state)}}
if(s_session.curmod==="3"){cards.switchCard(100)}var curCard=cards.get(s_session.curmod);if(global._card_aync){if(_menuData.illegal){curCard.params.normal=1}curCard.show(function(){if(_menuData.illegal){delete curCard.params.normal}})}else{curCard.rendered=true;curCard.noMore=!!parseInt(_menuData.isEnd,10);curCard.sessionId=global.s_session.sessionId}for(var i=0,syncRids=global.s_session.rids||[],l=syncRids.length;i<l;i++){curCard.ridsHash[syncRids[i]]=true}if(curCard.noMore){curCard.emitNoMore(
)}feedFirstLoad(curCard.id,!parseInt(_menuData.isEnd,10));setTimeout(function(){ctx.fire("modShow",{showTab:cards.curId,opType:"refresh"});card_showLog.itemShowLog()},1e3)}var _menuHelper={latestY:$(global).scrollTop(),barTop:_menuContainer.offset().top,barHeight:_centerMen.height(),topWrap:$("#s_top_wrap"),centTop:_centContent.offset().top+parseInt(_centContent.css("padding-top"),10),showed:false,overCenter:false,menuGurd:$("#s_menu_gurd",_topDom),container:$(".s-menu-container",_topDom),
toolBar:$("#s_top_feed",_topDom),toolBarTop:Math.min(parseInt($("#s_top_feed",_topDom).css("top"),10),300),menuStatus:cards.options("menuStatus",0),toggleMenu:function(scrollTop){if($.isIE===6){return}var _ctx=this;if(scrollTop===_ctx.latestY){return}var measure=$.isIE===7?10:3;if(scrollTop<_ctx.latestY&&_ctx.barTop-scrollTop<=_ctx.topWrap.height()+measure){if(!_ctx.showed){cards.toggleMenu(true);_ctx.showed=true;cards.options("menuStatus",1)}}else{
var noAnimate=_ctx.barTop-scrollTop>_ctx.topWrap.height()+measure;if(_ctx.showed){cards.toggleMenu(false,noAnimate);_ctx.showed=false}if(_ctx.barTop-scrollTop>_ctx.topWrap.height()){cards.options("menuStatus",0)}else{cards.options("menuStatus",2)}}if(_ctx.centTop-scrollTop<_ctx.topWrap.height()){if(!_ctx.overCenter){ctx.fire("overCenter",{over:true});_ctx.overCenter=true}}else{if(_ctx.overCenter){ctx.fire("overCenter",{over:false});_ctx.overCenter=false}}_ctx.latestY=scrollTop},
judgeMenu:function(top){var _ctx=this;var bottom1="228px";var bottom2="184px";if(top>0){if(window.isNewGridCard){_ctx.toolBar.show()}else{_ctx.toolBar.find(".to-top").css({visibility:"visible"})}$("#s_popup_advert").find(".advert-shrink").css({bottom:bottom1,transition:"none","-webkit-transition":"none","-moz-transition":"none","-o-transition":"none"})}else{if(window.isNewGridCard){_ctx.toolBar.hide()}else{_ctx.toolBar.find(".to-top").css({visibility:"hidden"})}$("#s_popup_advert").find(
".advert-shrink").css({bottom:bottom2,transition:"none","-webkit-transition":"none","-moz-transition":"none","-o-transition":"none"})}},initAdjust:function(){var headDom=$("#head_wrapper");$(global).on("unload",function(){$(".s-news-rank-wrapper",_topDom).hide();headDom.removeClass("s-down");global.scrollTo(0,0)})},feedRoller:function(scrollTop){if($.isIE!==6){return}var _ctx=this;var _top=Math.min(_ctx.toolBarTop+scrollTop,_centContent.height()-_ctx.toolBar.height());_ctx.toolBar.css({top:_top}
)},initToolBar:function(IE6){var self=this;self.toolBar.css({visibility:"visible"});if(IE6){return}self.resetToolPos();$(global).on("resize",self.resetToolPos);$(global).on("scroll",self.resetToolPos);$(global).on("s-skinoff",self.resetToolPos);$(global).on("s-skinon",self.resetToolPos)},removeToolCalc:function(){var self=this;if($.isIE===6){return}self.resetToolPos(true)},resetToolPos:function(animate){var self=_menuHelper;var toolTop;var nomalTop;var minTop
;var effect=animate===true?"animate":"css";if(!_loadHelper.loaded){nomalTop=$(global).height()-self.toolBar.height()-10;var maxTop=_centContent.offset().top+_centContent.outerHeight()-self.toolBar.height()-$(global).scrollTop()-1;minTop=_centContent.offset().top+217-$(global).scrollTop();toolTop=Math.max(Math.min(nomalTop,maxTop),minTop)}else{nomalTop=$(global).height()-self.toolBar.height()-30;minTop=_centContent.offset().top+227-$(global).scrollTop();toolTop=Math.max(nomalTop,minTop)}if(
self.rememberTop!==toolTop){self.toolBar[effect]({top:toolTop});self.rememberTop=toolTop}if($(window).width()<1e3){self.toolBar.css({left:501-$(window).scrollLeft()})}else{self.toolBar.css({left:"50%"})}}};function forceMenu(){cards.toggleMenu(true);_menuHelper.showed=true;cards.options("menuStatus",1)}function _bindEvent(){var cardChange=null;F.use("mancard:skeleton/toast");F.use("mancard:skeleton/card_refresh",function(AutoRefresh){var listenId=2;var isHit=window.bds.comm.sampleval.indexOf(
"new_homepage")>=0;if(!isHit){return}var autoRefreshCard=cards.get(listenId);AutoRefresh.init({timeout:30*60,card:autoRefreshCard,refreshCallback:function(){_loadHelper.moreBar.remove();_topDom.find(".s-xmancard").removeClass("s-news-split");card_showLog.feedLoadLog("autoRefresh")}})});card_showLog.feedLoadLog("firstRefresh");_centerMen.delegate(".s-menu-item","click",function(e){var $this=$(this);var id=$this.attr("data-id");var fromCardId=cards.curId;!!sampleval&&_loadHelper.handleDeskTop({
click:true},$this);if(cards.curId!==id){cards.switchCard(id,function(){feedFirstLoad(id,!parseInt(cards.get(cards.curId).waterPage,10)&&!cards.get(cards.curId).noMore)});_loadHelper.toggleMore(!parseInt(cards.get(cards.curId).waterPage,10)&&!cards.get(cards.curId).noMore);ctx.fire("switchCard",{toCard:id,fromCard:fromCardId})}if(id==="100"){_topDom.find(".mine-tips").hide()}F.use("mancard:setting/card_setting",function(Cardsetting){Cardsetting.hide()});setTimeout(function(){ctx.fire("modShow",{
showTab:cards.curId,opType:"click"});ctx.fire("modClick",{clickTab:cards.curId});card_showLog.itemShowLog()},500);F.use("superman:common/user_attr",function(userAttr){if(userAttr.getAttr&&userAttr.getAttr("firstMahattan")){var ids=cards.getMenuIDS().join(",");$.ajaxpost(s_domain.baseuri+"/pcweb/submit/mancardmod",{cmd:"sort",ids:ids});userAttr.setAttr("firstMahattan","off")}});e.stopPropagation()}).delegate(".s-menu-item","mouseenter",function(e){var elem=$(this);var id=elem.attr("data-id")
;var start=+new Date;_loadMap[id]={start:start};_loadMap[id].timeId=setTimeout(function(){if(!cards.get(id).rendered){cards.get(id).render()}},150);e.stopPropagation()}).delegate(".s-menu-item","mouseleave",function(e){var elem=$(this);var id=elem.attr("data-id");var cur=_loadMap[id];var end=+new Date;if(cur&&cur.start){if(end-cur.start<150){clearTimeout(cur.timeId)}}e.stopPropagation()}).delegate(".s-menu-setting","click",function(e){F.use("mancard:setting/card_setting",function(Cardsetting){
if(!Cardsetting.isShow()){Cardsetting.show({current:$("#s_menus_wrapper").find(".current").attr("data-id")})}else{Cardsetting.hide()}})}).delegate(".s-music-entry","mouseenter",function(){F.call("newmusic:player_exp","init")});_topDom.delegate(".s-more-bar","click",function(e){_loadHelper.tolerance=_loadHelper.defaulSub;_loadHelper.judgeFire();ctx.fire("loadMoreClick");e.stopPropagation()}).delegate(".to-top","click",function(e){$("body,html").animate({scrollTop:0});ctx.fire("gotoTopClick")
;e.stopPropagation()});_topDom.delegate("#s_top_feed .to-top","mouseenter mouseleave",function(e){if(e.type==="mouseenter"){$(this).addClass("icon-over");$("#s_qrcode_feed .qrcode-tooltip").hide()}else if(e.type==="mouseleave"){$(this).removeClass("icon-over")}e.stopPropagation()}).delegate("#s_qrcode_feed .qrcode-layer","mouseenter mouseleave",function(e){if(e.type==="mouseenter"){$(this).addClass("icon-over");$(this).next(".qrcode-tooltip").show().addClass("popup")}else if(
e.type==="mouseleave"){$(this).removeClass("icon-over");$(this).next(".qrcode-tooltip").removeClass("popup")}e.stopPropagation()});ctx.listen(["mancard:setting/card_setting","superman:common/bottom_layer","superman:mngr/menu_common"],["hideMain","showSet","hideSet"],function(data){var wraper;if(data.cmd==="add"){(cards.get(data.id)||cards.add(data.id,data.name,"1")).add2Men();cardChange=data.id}else if(data.cmd==="del"){var first=0;cards.get(data.id).del4Men();for(first in cards.pool){break}
cardChange=first}else if(data.cmd==="sort"){wraper=$("#s_menus_wrapper");$.each(data.ids,function(idx,item){cards.get(item).getMyMen().appendTo(wraper)})}else if(data._EVENT_NAME==="hideMain"){var delay=$("#s_top_wrap").hasClass("s-down")?$.isIE===8||$.isIE===7?2500:400:0;$("html,body").animate({scrollTop:0},delay,function(){$("#head_wrapper").addClass("s-ps-islite");$("#s_main").hide();$("#s_mancard_newmusic").hide();$("#s_mancard_newmusic").remove();$("#s_upfunc_menus .s-lite").removeClass(
"hide-icon");$("#bottom_layer .s-bottom-layer-right").addClass("hide-card");$("#s-user-setting-menu").addClass("hiding-feed");$(".s_form_wrapper").addClass("lite");if(s_session.isLogin){F.use("superman:common/user_attr",function(e){e.setAttr("isLite",true)})}});$("body").addClass("is-lite")}else if(data._EVENT_NAME==="showSet"){cardChange=null}else if(data._EVENT_NAME==="hideSet"){cardChange=null;wraper=$("#s_menus_wrapper");var currentIds=cards.getMenuIDS();var sMenuMusic=$(".s-menu-music");if(
sMenuMusic.length>0&&sMenuMusic.css("display")!=="none"){currentIds.unshift(sMenuMusic.attr("data-id"))}$.each(currentIds,function(idx,item){if($.inArray(item,data.ids)===-1){if(item==="3"){sMenuMusic.find(".s-music-entry").hide();F.call("newmusic:index","stop")}cards.get(item).del4Men();cards.get(item).getMyMen().removeClass("current")}});$.each(data.items,function(idx,item){if(cards.get(item.id)){var node=cards.get(item.id).getMyMen();node.css("display","");if(item.id==="3"){node.appendTo(
wraper.parent());sMenuMusic.find(".s-music-entry").show();$("#s_mancard_newmusic").show();F.call("newmusic:index","init")}else{node.appendTo(wraper)}if(node.hasClass("current")){cardChange=item.id}}else{cards.add(item.id,item.name,"1").add2Men()}});if(data.items.length===0||data.items.length===1&&data.ids[0]==="3"){cardChange="100"}if(s_session.curmod==="100"){return}if(cardChange!==s_session.curmod){if(cardChange!==null){cards.switchCard(cardChange)}else{
cardChange=data.ids[0]==="3"?data.ids[1]:data.ids[0];cards.switchCard(cardChange)}}}});ctx.listen("superman:page/scroll","outMenu",function(data){if(!data.out){$("#s_top_wrap .s-top-nav").css("display","none")}});_loadHelper.moreUpFy();$(global).bind("resize",function(e){windowHeight=$(this).height();_menuHelper.barTop=_menuContainer.offset().top;_loadHelper.moreUpFy(undefined,true)}).on("scroll",function(e){if(s_session.index_off||s_session.index_guide){return}var scrollTop=$(this).scrollTop()
;var totalHeight=$(document).height();if(Math.abs(scrollTop+windowHeight-totalHeight)<=_loadHelper.tolerance&&_loadHelper.preTop<scrollTop){_loadHelper.judgeFire()}_loadHelper.preTop=scrollTop;_menuHelper.judgeMenu(scrollTop);_menuHelper.toggleMenu(scrollTop);_menuHelper.feedRoller(scrollTop);setTimeout(function(){card_showLog.itemShowLog()},300);_loadHelper.moreUpFy(undefined,true)});$(global).on("s-skinon",function(){_loadHelper.moreUpFy(true)});$(global).on("s-skinoff",function(){$(window
).trigger("desktopSkinOff");_loadHelper.moreUpFy(false)});var ua=navigator.userAgent.toLowerCase();var isPad=ua.match(/iPad/i)&&ua.match(/iPad/i)[0]==="ipad"||navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1;if(isPad){var startY=0;var endY=0;$(document).on("touchstart",function(e){startY=e.originalEvent.changedTouches[0].pageY}).on("touchend",function(e){endY=e.originalEvent.changedTouches[0].pageY;if(endY-startY<0){_loadHelper.tolerance=_loadHelper.defaulSub;_loadHelper.judgeFire()}}
)}$(document).on("mousewheel",function(e){reload(e)}).on("keydown",reload);function reload(e){if(s_session.index_guide){return}if(document.documentElement.scrollHeight<=document.documentElement.clientHeight&&e.deltaY<0||$(global).scrollTop()+$(global).height()-$(document).height()>=-2&&_loadHelper.tolerance===0&&(e.deltaY<0||e.keyCode===40)){_loadHelper.tolerance=_loadHelper.defaulSub;_loadHelper.judgeFire()}}var bottomChange=false;ctx.listen("mancard:skeleton/card","beforeLoading",function(){
if(!bottomChange){$("#bottom_container").appendTo("#s_wrap");bottomChange=true}})}!!sampleval&&desktopEvent();exports.init=init;exports.forceMenu=forceMenu;exports.judgeFire=function(){_loadHelper.tolerance=300;_loadHelper.judgeFire()}});F.call("mancard:skeleton/presenter","init");
F.module("mancard:skeleton/card_tab",function(require,exports,ctx){var cards=require("skeleton/card_collection");var re=/childId=(.+);/;var reLasttab=/lasttab/;function CardTab(options){this.initialize(options)}CardTab.prototype={initialize:function(options){var self=this;var option=F.mix({cardName:null,componentWrap:null,content:null,cardTabClass:"card-tab",tabNameClass:"tab-name",tabNameCurClass:"tab-name-cur",tabContentClass:"tab-content",tabContentWrapClass:"tab-content-wrap",
dataTabName:"data-childid"},options);self.cardName=option.cardName;self.componentWrap=option.componentWrap;self.content=option.content;self.tabNameClass=option.tabNameClass;self.tabNameCurClass=option.tabNameCurClass;self.tabContentClass=option.tabContentClass;self.dataTabName=option.dataTabName;self.mainDom=self.componentWrap.parent();var id=self.mainDom.attr("data-id");self.card=cards.get(id);self.sessionIds={};self.offsets={};self.noMores={};self.dataWaterPara="";self.render(option)
;self.bindEvent()},render:function(options){var self=this;self.tabs=self.componentWrap.find("."+options.cardTabClass);self.curTab=self.tabs.find("."+self.tabNameCurClass).attr(self.dataTabName);self.dataWaterPara=self.mainDom.attr("data-waterpara")||"";if(!self.dataWaterPara.match(re)){self.dataWaterPara=self.dataWaterPara+"childId="+self.curTab+";";self.mainDom.attr("data-waterpara",self.dataWaterPara)}self.componentWrap.attr("data-curtab",self.curTab);self.content.wrap(
'<div class="'+options.tabContentWrapClass+'"></div>');self.contentWrap=self.componentWrap.find("."+options.tabContentWrapClass);self.content.addClass("tab-content").attr(self.dataTabName,self.curTab).attr("data-load","loaded").show();self.sessionIds[self.curTab]=self.card.sessionId;self.offsets[self.curTab]=self.card.waterPage;self.noMores[self.curTab]=self.card.noMore},bindEvent:function(){var self=this;var tpl=['<div class="s-content-load s-opacity-white-background">',
'<img src="#{staticUrl}static/mancard/img/loading-f9b765014b.gif" />',"<div>加载中，精彩马上呈现</div>","</div>"].join("");tpl=$.formatString(tpl,{staticUrl:s_domain.staticUrl});var targetTabglobal;ctx.listen("mancard:skeleton/card",["syncNomore"],function(data){self.sessionIds[targetTabglobal]=self.card.sessionId;self.card.sessionId=self.sessionIds[self.curTab];self.card.noMore=true;self.noMores[targetTabglobal]=self.card.noMore;self.contentWrap.find("["+self.dataTabName+'="'+targetTabglobal+'"]').attr(
"data-load","loaded").append(data);self.card.setForceLoad(false)});self.tabs.delegate("."+self.tabNameClass,"mouseenter",function(e){var that=this;var preName=$(this).prop("className");if(reLasttab.exec(preName)&&reLasttab.exec(preName)[0]==="lasttab"){return}var targetTab=$(this).attr(self.dataTabName);targetTabglobal=targetTab;var targetContent=self.contentWrap.find("["+self.dataTabName+'="'+targetTab+'"]');if(targetContent.length===0){targetContent=$(
'<div class="'+self.tabContentClass+'"></div>').attr(self.dataTabName,targetTab).appendTo(self.contentWrap);targetContent.attr("data-load","loading").append(tpl);self.card.setForceLoad(true);self.card.addParam("childId",targetTab);self.card.load(function(data){self.sessionIds[targetTab]=self.card.sessionId;self.card.sessionId=self.sessionIds[self.curTab];self.card.noMore=self.noMores[targetTab]||false;self.noMores[targetTab]=self.card.noMore;self.card.ridsHash={};targetContent.attr("data-load",
"loaded").append(data);self.card.setForceLoad(false);if(self.curTab===targetTab){if(!$(that).attr("data-firstLoad")){self.card.waterLoading=false;self.card.appendData(function(data){$("#s_mancard_main").find(".s-more-bar").hide();$(that).attr("data-firstLoad",1)},false,targetContent)}}self.contentWrap.find(".s-content-load").remove()})}}).delegate("."+self.tabNameClass,"click",function(e){var that=this;e.stopPropagation();var preName=$(this).prop("className");if(reLasttab.exec(preName
)&&reLasttab.exec(preName)[0]==="lasttab"){ctx.fire("clicklastTab");return}$(that).trigger("mouseenter");var curTab=self.tabs.find("."+self.tabNameCurClass).removeClass(self.tabNameCurClass).attr(self.dataTabName);var targetTab=$(this).addClass(self.tabNameCurClass).attr(self.dataTabName);self.dataWaterPara=self.dataWaterPara.replace(re,"childId="+targetTab+";");self.mainDom.attr("data-waterpara",self.dataWaterPara);ctx.fire("clickTab",{tabName:$(this).prop("className"),childId:$(this).attr(
"data-childid")});if(curTab===targetTab){return}self.offsets[curTab]=self.card.waterPage;self.noMores[curTab]=self.card.noMore;self.card.waterPage=self.offsets[targetTab]||0;self.card.noMore=self.noMores[targetTab]||false;self.card.ridsHash={};self.card.sessionId=self.sessionIds[targetTab];if(!self.card.noMore){self.card.resetNoMore()}else{$(".load-done").remove();$(".s-content-load").remove();self.card.emitNoMore()}var curContent=self.contentWrap.find("["+self.dataTabName+'="'+curTab+'"]')
;var targetContent=curContent.siblings("["+self.dataTabName+'="'+targetTab+'"]');curContent.hide();targetContent.show();self.curTab=targetTab;if(self.card.id!="5"){self.setTargetTab(targetTab)}self.card.waterDom=targetContent;if(!self.sessionIds[targetTab]){return}self.card.waterLoading=false;if(!$(that).attr("data-firstLoad")){self.card.appendData(function(data){$("#s_mancard_main").find(".s-more-bar").hide();$(that).attr("data-firstLoad",1)},false,targetContent)}})},setTargetTab:function(tab,
cb){var self=this;F.use("mancard:skeleton/card_memory",function(cardMemory){cardMemory.setCardTab(self.cardName,tab);cb&&cb()})}};return CardTab});
F.module("mancard:skeleton/card_refresh",function(require,exports,ctx){var LOADING_TIMEOUT={COMMON:3e3,FAIL:5e3};function checkEleInView(ele){var rect=ele.getBoundingClientRect();return rect.top>0&&rect.top+rect.height*.3<window.innerHeight-78}function checkIsFix(){return $("#s_top_wrap").hasClass("s-down")}function clearData(){var isFix=checkIsFix();var news=$(".s-news-item");function check(){if(!isFix){return 0}var flag=false;if(+$(".s-menu-item.current").data().id===2){for(
var i=0;i<news.length;i++){if(checkEleInView(news[i])){flag=true}else if(flag&&!checkEleInView(news[i])){return i}}}return news.length}var lastIndex=check();for(var i=lastIndex;i<news.length;i++){if(news[i]){news[i].parentElement.removeChild(news[i])}}return lastIndex-1}function easyScroll(){var min=Math.min;var ms=Date.now;function make(prop){return function scroll(el,to,opts,cb){opts=opts||{};if(typeof opts=="function")cb=opts,opts={};if(typeof cb!="function")cb=function(){};var start=ms()
;var from=$(window).scrollTop();var ease=opts.ease||inOutSine;var duration=!isNaN(opts.duration)?+opts.duration:350;var cancelled=false;return requestAnimationFrame(animate),cancel;function cancel(){cancelled=true}function animate(){if(cancelled)return;var now=ms();var time=min(1,(now-start)/duration);var eased=ease(time);el.scrollTo(0,eased*(to-from)+from);time<1?requestAnimationFrame(animate):requestAnimationFrame(function(){cb(null,el[prop])})}}}function inOutSine(n){return.5*(1-Math.cos(
Math.PI*n))}return make("scrollTop")}var scrollTop=easyScroll();function AutoRefresh(options){this.isStart=false;this.init(options)}AutoRefresh.prototype={init:function(options){if(!options){return}this.card=options.card;this.$newsWrapper=$(".s-news-wrapper");this.$topWrap=$("#s_top_wrap");this.$cardMain=$("#s_mancard_main");this.$toastWrapperDiv=null;this.$toastSpan=null;this.refreshCallback=options.refreshCallback||function(){};this.$tabDom=$(".s-menu-item[data-id="+this.card.id+"]");if(
this.$tabDom.length<=0){return}this.timeout=options.timeout;this.leaveTime=null;this.returnTime=null;this.startListen()},startListen:function(){var _this=this;if(_this.isStart){return}this.initToast();_this.isStart=true;_this.listener=function listener(target){if(document.visibilityState==="visible"){_this.returnTime=_this._timestampToSeconds(Date.now());if(_this.checkNeedRefresh()){_this.refresh()}}else{_this.leaveTime=_this._timestampToSeconds(Date.now())}};document.addEventListener(
"visibilitychange",_this.listener)},checkAds:function(){var news=$(".s-news-item");var lastAdIndex=0;var lastIndex=0;if(!checkIsFix()){return 0}for(var i=0;i<news.length;i++){if(checkEleInView(news[i])){if(news.eq(i).find(".ad-icon").length>0){lastAdIndex=i}lastIndex=i}}return lastIndex-lastAdIndex<2?0:1},refresh:function(){var _this=this;_this.showToast();_this.setToast("loading","即将为你呈现新鲜内容");_this.addBottomLoading();_this.card.autoRefreshing=true;clearTimeout(_this.failTimeout);if(checkIsFix(
)){clearData()}var needAd=_this.checkAds();_this.loadData(_this.getParams({needAd:needAd}),function(data){if(!checkIsFix()){clearData()}_this.card.autoRefreshing=false;_this.setToast("suc","为你推荐最新内容");var scrollNewsItem=_this.getCurrentNews();if(!_this.card.waterDom){_this.card.waterDom=$(".water-container",_this.card.mainDom)}_this.card.waterDom.append(data.html);_this.removeBottomLoading();typeof _this.refreshCallback==="function"&&_this.refreshCallback();if(checkIsFix()){setTimeout(function(
){scrollTop(window,scrollNewsItem.newsItem.height()+scrollNewsItem.newsItem.offset().top-30)},window.innerHeight>600?400:240)}setTimeout(function(){_this.closeToast()},LOADING_TIMEOUT.COMMON)})},getCurrentNews:function(){var news=$(".s-news-item");var index=news.length-1;return{index:index,newsItem:news.eq(index)}},getParams:function(p){var _card=this.card;var params={id:_card.id,offset:_card.waterPage,sessionId:_card.sessionId,crids:window.s_session.crids,refresh_state:4,async:1,needAd:p.needAd
};var paraDom=_card.mainDom||$("#s_content_"+_card.id);var extraParam=paraDom.attr("data-waterpara");if(!extraParam&&paraDom.find(".s-xmancard").attr("data-waterpara")){extraParam=paraDom.find(".s-xmancard").attr("data-waterpara")}if(extraParam){var regx=/([s\S]*?)\=([\s\S]*?)\;/g;var result=null;while(result=regx.exec(extraParam)){if(result[1]==="offset"){if(!_card.offsetUsed){params[result[1]]=result[2];_card.waterPage=result[2];_card.offsetUsed=true}}else{params[result[1]]=result[2]}}}
params.newsNum=params.newsNum||params.pos;return params},addBottomLoading:function(){var $loading=$(".s-loading");if(this.card.loadDom){this.card.loadDom.show()}if($loading.find(".s-auto-refresh-loading").length===0){$loading.append('<div class="s-auto-refresh-loading">精彩内容马上呈现</div>')}},removeBottomLoading:function(){if(this.card.loadDom){this.card.loadDom.hide()}$(".s-auto-refresh-loading").remove()},_timestampToSeconds:function(timestamp){return Math.floor(timestamp/1e3)},
checkNeedRefresh:function(){if(!this.$tabDom.hasClass("current")){return}return this.returnTime-this.leaveTime>this.timeout},loadData:function(params,cb){var _this=this;F.use("mancard:skeleton/model",function(dao){dao.get("waterHtml",function(data){typeof cb==="function"&&cb(data);$("div[data-waterpara]").attr("data-waterpara","version="+data.version+";"+data.waterpara);_this.card.waterPage++},params).fail(function(){_this.setToast("retry","刷新失败，点击重试");_this.card.autoRefreshing=false})})},
initToast:function(){var _this=this;var toastWrapperDiv=document.createElement("div");var toastSpan=document.createElement("span");if(this.$newsWrapper.find(".auto-refresh-toast-wrapper").length>0){return}toastWrapperDiv.className="auto-refresh-toast-wrapper";toastWrapperDiv.style.display="none";toastSpan.className="auto-refresh-toast";this.$toastWrapperDiv=$(toastWrapperDiv);this.$toastSpan=$(toastSpan);this.$toastWrapperDiv.append(toastSpan);this.$newsWrapper.append(this.$toastWrapperDiv)
;_this.changeToastPosition();if(this._initToastEvent){return}_this.$newsWrapper.on("click",".auto-refresh-toast-wrapper",function(){if(_this.$newsWrapper.find(".auto-refresh-toast").hasClass("retry")){_this.refresh()}_this.failTimeout=setTimeout(function(){_this.closeToast()},LOADING_TIMEOUT.FAIL)});window.addEventListener("scroll",function(){_this.changeToastPosition()});window.addEventListener("resize",function(){_this.changeToastPosition()});this._initToastEvent=true},
changeToastPosition:function(e){if(checkIsFix()){this.$newsWrapper.find(".auto-refresh-toast-wrapper").css({position:"fixed",top:44+this.$topWrap.height()+"px",left:this.$cardMain.offset().left})}else{this.$newsWrapper.find(".auto-refresh-toast-wrapper").css({position:"absolute",left:"0",top:"42px"})}},setToast:function(iconClass,str){this.showToast();var $toast=this.$newsWrapper.find(".auto-refresh-toast");$toast.removeClass("loading");$toast.removeClass("retry");$toast.removeClass("suc")
;$toast.addClass(iconClass);this.$newsWrapper.find(".auto-refresh-toast").html('<span class="auto-refresh-icon"></span>'+str)},showToast:function(){this.$newsWrapper.find(".auto-refresh-toast-wrapper").css("display","block")},closeToast:function(){this.$newsWrapper.find(".auto-refresh-toast-wrapper").css("display","none")}};return new AutoRefresh});
F.module("mancard:skeleton/toast",function(require,exports,tool){function checkIsFix(){return $("#s_top_wrap").hasClass("s-down")}var TOAST_DEFAULT_NAME="default";var defaultTimeout=3e3;var defaultParentSelector=$("body");var iconType={LOADING:"loading",SUCCESS:"success",RETRY:"retry",NONE:"none"};var modeType={fixInMiddle:"fixInMiddle",flexible:"flexible"};function Toast(options){this.reset(options);this._timeout=null;this._el=null}Toast.prototype={reset:function(options){
this.$parentSelector=$(options.parentSelector||document.body);if(this.$parentSelector.length>1){this.$parentSelector=this.$parentSelector.eq(0)}this.mode=options.mode||modeType.fixInMiddle;this.name=options.name||TOAST_DEFAULT_NAME;this.timeout=options.timeout||2e3;this.text=options.text;this.icon=options.icon;this.flexibleOptions=options.flexibleOptions||{fixTop:"170px"};this._changePositionFunc=null;window.removeEventListener("resize",this._changePositionFunc);window.removeEventListener(
"scroll",this._changePositionFunc)},renderString:function(){var parentWidth=this.$parentSelector.width();return'<div class="bd-pc-toast-wrapper" style="width: '+parentWidth+'px;">'+'<div class="bd-pc-toast">'+'<div class="bd-pc-toast-icon '+(this.icon?this.icon:"hide-icon")+'"></div>'+this.text+"</div>"+"</div>"},show:function(options){var _this=this;if(_this.isShowing){return}_this.isShowing=true;clearTimeout(_this._timeout);_this.close();_this.reset(options);_this._timeout=setTimeout(function(
){_this.close()},_this.timeout);var htmlStr=_this.renderString();_this._el=$(htmlStr);_this.setStyleByMode();_this.$parentSelector.append(_this._el);setTimeout(function(){_this.isShowing=false},10)},setStyleByMode:function(){var _this=this;switch(_this.mode){case modeType.fixInMiddle:_this._el.css({position:"fixed",left:"50%",top:"50%",transform:"translate(-50%, -50%)"});break;case modeType.flexible:_this._changePositionFunc=function(){if(checkIsFix()){_this._el.css({position:"fixed",
left:_this.$parentSelector.offset().left,top:"50%"})}else{_this._el.css({position:"absolute",left:"0",top:_this.flexibleOptions.fixTop})}};_this._changePositionFunc();window.addEventListener("resize",_this._changePositionFunc);window.addEventListener("scroll",_this._changePositionFunc);break;default:}},close:function(){if(this._el){this._el.remove();window.removeEventListener("resize",this._changePositionFunc);window.removeEventListener("scroll",this._changePositionFunc)}}};var toast=new Toast({
parentSelector:defaultParentSelector,icon:iconType.NONE,timeout:defaultTimeout,name:TOAST_DEFAULT_NAME,text:"",mode:modeType.fixInMiddle,flexibleOptions:{fixTop:"170px"}});window._toast=toast;return toast});
F.module("mancard:setting/card_setting",function(require,exports,ctx){var Emitter=require("superui:util/emitter"),Dot=require("superui:util/dot"),userAttr=require("superman:common/user_attr"),DotCardCompile=Dot.compile(['<div class="s-cardsetting" id="s_content_99" data-id="99">','<div class="s-cardsetting-wrap clearfix">','<div class="s-cardsetting-left">',"<h3>已订阅频道</h3>",
'<div style="float:left;width:78px;text-align:center;margin-top:18px;border:1px solid #cdcdcd;height:24px;line-height:24px;">我的关注</div>','<div class="s-cardsetting-content">',"{{~it.selected :value:index}}",'{{? (value.name!="音乐")}}','<div class="s-mod-item" id="s_moditem_{{=value.id}}" data-id="{{=value.id}}" data-imgname="{{=value.imgname}}" data-name="{{=value.name}}"{{ if(value.name == "音乐"&&!it.showMusic){ }} style="display:none;"{{ } }}>','<div class="s-mod-icon">',"</div>",
'<div class="s-mod-title">',"{{=value.name}}","</div>","</div>","{{?? it.showMusic}}",'<div class="s-mod-item s-mod-music s-mod-undraggable" id="s_moditem_{{=value.id}}" data-id="{{=value.id}}" data-imgname="{{=value.imgname}}" data-name="{{=value.name}}"{{ if(value.name == "音乐"&&!it.showMusic){ }} style="display:none;"{{ } }}>','<div class="s-mod-icon">',"</div>",'<div class="s-mod-title">',"{{=value.name}}","</div>","</div>","{{?}}","{{~}}",'<div class="noremove-tips">',
'<p>亲，就剩我老哥一个了，不能再删了~可以尝试点击右下角“<a class="tips-hide" href="javascript:void(0)">隐藏卡片</a>”收起全部内容。</p>','<b class="close-icon" title="关闭"></b>',"</div>",'<div class="drag-tips">','<p>拖动可以排序<a class="i" href="javascript:void(0)">我知道了</a></p>',"<b></b>","</div>","</div>","</div>",'<div class="s-cardsetting-right">',"<h3>未订阅频道</h3>",'<div class="s-cardsetting-content">',"{{~it.unselected :value:index}}",'{{? (value.name!="音乐")}}',
'<div class="s-mod-item" id="s_moditem_{{=value.id}}" data-id="{{=value.id}}" data-imgname="{{=value.imgname}}" data-name="{{=value.name}}"{{ if(value.name == "音乐"&&!it.showMusic){ }} style="display:none;"{{ } }}>','<div class="s-mod-icon">',"</div>",'<div class="s-mod-title">',"{{=value.name}}","</div>","</div>","{{?? it.showMusic}}",
'<div class="s-mod-item s-mod-music s-mod-undraggable" id="s_moditem_{{=value.id}}" data-id="{{=value.id}}" data-imgname="{{=value.imgname}}" data-name="{{=value.name}}"{{ if(value.name == "音乐"&&!it.showMusic){ }} style="display:none;"{{ } }}>','<div class="s-mod-icon">',"</div>",'<div class="s-mod-title">',"{{=value.name}}","</div>","</div>","{{?}}","{{~}}","</div>","</div>","</div>",'<div class="s-cardsetting-set-wrapper">','<div class="s-cardsetting-set clearfix">',"{{? it.expand}}",
"{{~it.expand :value:index}}","{{? value.tipsunknown}}",'<span class="scene-recomm-unknown"></span>',"{{?}}",'<a href="#" onclick="return false;"  class="hide-mods {{=value.otherClassName}}"  hidefocus><span class="{{=value.borderClass}} {{=value.reviewCheck}}" id="{{=value.myId}}" data-attr="{{=value.tips}}"></span><span>{{=value.description}}</span></a>',"{{~}}",
'<a href="#" onclick="return false;" class="hide-mods" id="s_hide_allmods" hidefocus=""><span class="bg"></span><span>隐藏卡片</span></a>',"{{?}}","</div>","</div>","</div>"].join("")),TIPS='<div class="s-mod-tips">',TIPS_ADDTEXT="",TIPS_REMOVETEXT="拖动到这里可以取消订阅",ITEM_HOVER_CLASS="mod-hover",EXPAND_CLASS="hide-mods",EXPAND_CLASS_QUERY="."+EXPAND_CLASS,ITEM_CLASS="s-mod-item",ITEM_CLASS_QUERY="."+ITEM_CLASS,ITEM_LEFTCLASS_QUERY=".s-cardsetting-left .s-cardsetting-content",
ITEM_RIGHTCLASS_QUERY=".s-cardsetting-right .s-cardsetting-content",Draggselect=require("superui:component/draggselect"),UserAttr=require("superman:common/user_attr"),Dialog=require("superui:component/dialog"),componentLog=require("superui:component"),CANREMOVE=true,FromDrag=false,cards=require("skeleton/card_collection"),URLS={mod:s_domain.baseuri+"/pcweb/submit/mancardmod",menu:s_domain.baseuri+"/pcweb/submit/mancardmenu"},musicId;var _dragItem=null;function Cardsetting(){this.initialize()}
Cardsetting.prototype={constructor:Cardsetting,initialize:function(){this.main=$("#s_main");this.textarea=$("#s_menus_textarea");this.addedcache=[];if(this.textarea.length){this.selected=[];this.unselected=[];this.cache=$.parseJSON(this.textarea.val());this.render()}this.__datas=[]},renderTips:function(){var tips,self=this;self.dialog.body.on("click",".scene-recomm-unknown",function(){if(!tips){F.use("superui:component/tips",function(Tips){var unknown=$(".scene-recomm-unknown",self.dialog.body)
;tips=new Tips({componentWrap:self.dialog.body,target:unknown,identity:"scene-recommend",content:['<div class="scene-recommend-content">','<div class="scene-recommend-content">',"<h2>情景推荐模式：</h2>",'<p class="title">即当您登录百度首页时，页面会优先切换到您此时可能感兴趣的内容。</p>',"<p>例：您习惯看各种资讯，一大早打开电脑，会优先给您推荐新闻；闲暇时会给您切换至视频卡片供您舒缓神经。</p>",'<p class="last s-opacity-border4-top">如若您不喜欢，取消勾选框中的√即可，感谢您的使用~</p>',"</div>"].join(""),align:"center",arrowLeft:"right",autoShow:false,hasClose:false,width:388,theme:"scene-recommend"})})
}tips.show()})},render:function(){var self=this,expand=[];var myItem=null;F.each(self.cache.data,function(item){if(+item.id===100){myItem=item}if(+item.ismenu===1){if(+item.state===1){if(+item.id===3){self.selected.unshift(item);if(!window.s_session.audioModernizr){musicId=item.id}}else{self.selected.push(item)}}else{self.unselected.push(item)}}});if(s_session.strategy_hit===2){expand.push({otherClassName:"content-mod",borderClass:"choice-border",tips:"mouseScrollGuide",myId:"mouseScroll_mod",
description:"滚轮切换卡片",reviewCheck:s_session.userTips["mouseScrollGuide"]?"checked":""})}expand.push({otherClassName:"content-mod",borderClass:"choice-border",tips:"conRecommendTip",myId:"conRecommend_mod",description:"情景推荐",tipsunknown:true,reviewCheck:s_session.userTips["conRecommendTip"]?"checked":""});self.expand=expand},init:function(){var self=this;dialog=self.dialog;dialog.body.on("mouseenter mouseleave",ITEM_CLASS_QUERY,function(event){var target=$(event.target).closest(ITEM_CLASS_QUERY)
;target[event.type=="mouseenter"?"addClass":"removeClass"](ITEM_HOVER_CLASS)});self.bindDrag();dialog.on("onHide",function(cur){$("#s_main").removeClass("sui-cardsetting-main");s_session.skeleton_stopanimated=false;var items=self.getItems(),data={};ctx.fire("hideSet",items);self.dialog.log("hide")});self.bindEvent()},bindEvent:function(){var self=this,iKonwNode=self.dialog.body.find(".drag-tips"),hideNode=self.dialog.body.find(".tips-hide"),closeTipsNode=self.dialog.body.find(".close-icon")
;iKonwNode.on("click",function(){F.use("common/user_attr",function(e){e.setAttr("settingDragTips",false);iKonwNode.css("display","none")})});hideNode.on("click",function(e){self.hideMain();e.stopPropagation()});$(document).on("mousedown",function(e){if($(e.target).hasClass("menu-icon")){return}self.hide();FromDrag=false});closeTipsNode.on("click",function(e){self.dialog.body.find(ITEM_LEFTCLASS_QUERY).find(".noremove-tips").css("display","none")});ctx.listen("mancard:skeleton/presenter",
"overCenter",function(data){if(!!data.over){self.hide()}});ctx.listen("mancard:skeleton/card_collection","showTopMenu",function(data){if(!data.show){self.hide()}});$(window).on("scroll",function(){})},save:function(){var self=this,packed=self.packed;setTimeout(function(){ctx.fire("modOperate",packed)},100)},pack:function(data){var self=this,ids,item=data.dragItem;self.packed={ismenu:1,cmd:data.type=="added"?"add":data.type=="remove"?"del":"sort"};ids=self.getIDS();self.packed.ids=ids.ids
;self.packed.names=ids.names;if(item){self.packed.id=item.attr("data-id");self.packed.name=item.attr("data-name")}self.save()},getIDS:function(){var ids={ids:[],names:[]},select=this.draggselect.selected,drags=select.drags,cache=select.cache;F.each(cache,function(item){var drag=drags.eq(item),dataid=drag.attr("data-id"),name=drag.attr("data-name");ids.ids.push(dataid);ids.names.push(name)});return ids},getItems:function(){var items=[],ids=[],select=this.draggselect.selected,drags=select.drags,
cache=select.cache;F.each(cache,function(item){var drag=drags.eq(item),dataid=drag.attr("data-id"),name=drag.attr("data-name");ids.push(dataid);items.push({name:name,id:dataid})});return{ids:ids,items:items}},tips:function(){var self=this,current,target,draggselect=self.draggselect;current=draggselect.selected;target=draggselect.unselected;if(!current.tipsmessage){current.tipsmessage=$(TIPS).html(TIPS_REMOVETEXT).appendTo(current.wrap)}if(!target.tipsmessage){target.tipsmessage=$(TIPS).html(
TIPS_ADDTEXT).appendTo(target.wrap)}if(current.total==0){target.tipsmessage.show();current.tipsmessage.hide()}else{target.tipsmessage.hide();if(target.total==0){target.tipsmessage.hide();current.tipsmessage.show()}else{current.tipsmessage.hide()}}target.tipsmessage.hide()},cacheAdded:function(data){var self=this,index,id,cache=this.addedcache;if(data.dragItem){id=data.dragItem.attr("data-id");index=$.inArray(id,cache);if(index>-1){cache.splice(index,1)}if(data.type=="added"){cache.push(id)}}},
bindDrag:function(){var self=this,dialog=self.dialog,leftHave;if(dialog.body.find(ITEM_LEFTCLASS_QUERY).width()>530){self.bugtotal=self.bugtotal||0;if(self.bugtotal++<100){return setTimeout(function(){self.bindDrag()},200)}}self.draggselect=new Draggselect({identity:"cardsetting",containment:dialog.body,selected:dialog.body.find(ITEM_LEFTCLASS_QUERY),unselected:dialog.body.find(ITEM_RIGHTCLASS_QUERY),dragsort:ITEM_CLASS_QUERY,cansort:false,afterAnimateTime:100});self.draggselect.on(
"onBeforeSelect",function(data){_dragItem=data.dragItem;_dragItem.css("zoom","0");var parent=data.dragItem.parent().parent();self.dialog.body.find(".drag-tips").css("display","none");if(data.dragItem){data.dragItem.removeClass(ITEM_HOVER_CLASS);if(_dragItem.text()==="音乐"){$(".sui-draggsort-holder").addClass("lock");self.draggselect.selected.__options.cansort=false}}});self.draggselect.on("onAfterSelect",function(data){setTimeout(function(){self.resort()},
self.draggselect.selected.__options.afterAnimateTime+50);self.draggselect.selected.__options.cansort=true;if(_dragItem){setTimeout(function(){_dragItem.css("zoom","1");_dragItem=null},50)}$(".sui-draggsort-holder").removeClass("lock")});self.draggselect.on("onBeforeSelectSwap",function(){self.dialog.body.find(".drag-tips").css("display","none");self.draggselect.selected.parentoffset=$(".s-cardsetting-left .s-cardsetting-content").offset();self.draggselect.unselected.parentoffset=$(
".s-cardsetting-right .s-cardsetting-content").offset()});self.draggselect.on("onSelectSwap",function(data){data.dragItem&&data.dragItem.removeClass("mod-hover");if(data.dragItem&&$.isIE){data.dragItem.removeClass("mod-hover");setTimeout(function(){},100)}self.checkLeave();switch(data.type){case"added":cmd="add";break;case"remove":cmd="del";var item=data.dragItem,img,src;self.cacheAdded(data);if(item&&item.length){if(data.type=="remove"){self.tips(true)}else{self.tips()}item.removeClass(
ITEM_HOVER_CLASS)}break;case"noremove":self.dialog.body.find(".drag-tips").hide();break;case"switch":cmd="sort";break}if(!_dragItem){self.resort()}self.pack(data);if(s_session.userTips.firstMahattan){F.use("superman:common/user_attr",function(userAttr){userAttr.setAttr("firstMahattan",false)})}$.ajaxpost(URLS.mod,{cmd:self.packed.cmd,id:data.dragItem?data.dragItem.attr("data-id"):undefined,ids:self.getModIds(self.packed.ids)},function(response){});var ids=cards.getMenuIDS()
;var newIds=self.getItems().ids;for(var i=0;i<ids.length;i++){var node=cards.get(ids[i]).getMyMen();if(node.hasClass("current")&&$.inArray(ids[i],newIds)==-1){$.ajaxpost(URLS.menu,{id:newIds[0]},function(response){})}}});self.draggselect.on("onAfterSelect",function(data){FromDrag=true;self.checkLeave()});self.draggselect.on("onResizeHeight",function(data){});self.draggselect.on("beforeMoving",function(){dialog.body.find(ITEM_LEFTCLASS_QUERY).find(".noremove-tips").css("display","none")})
;self.bindExpand();self.renderTips();self.tips(true);self.checkLeave()},checkLeave:function(){var self=this;leftHave=self.dialog.body.find(ITEM_LEFTCLASS_QUERY).find(ITEM_CLASS_QUERY).length;CANREMOVE=leftHave==1?false:true},bindExpand:function(){var self=this,dialog=self.dialog;dialog.body.on("click",function(event){var target=$(event.target).closest(EXPAND_CLASS_QUERY),span,expand,checked;if(target.length){span=target.find("span").eq(0);if(expand=span.attr("data-attr")){
checked=span.toggleClass("checked").hasClass("checked");UserAttr.setAttr(expand,checked);self.draggselect.log(expand,"checked="+checked)}else{self.draggselect.log("hidemain");self.hideMain()}return false}})},hideMain:function(onlyhide){if(!onlyhide){this.dialog.hide()}ctx.fire("hideMain")},show:function(data){var self=this,width;self.current=data.current;if(self.cache){if(!self.dialog){$("#s_main").addClass("sui-cardsetting-main");self.dialog=new Dialog({identity:"cardsetting",
width:width=self.main.width(),content:DotCardCompile({expand:self.expand,unselected:self.unselected,selected:self.selected,showMusic:window.s_session.audioModernizr}),position:function(){return{top:"36px",width:"895px",left:"0px"}},theme:"cardsetting",autoShow:false,hasMask:false,hasClose:false,componentWrap:$("#s_main"),hackToTop:false});self.dialog.on("onShow",function(){$("#s_main").addClass("sui-cardsetting-main");s_session.skeleton_stopanimated=true;if(!self.binded){setTimeout(function(){
self.init(self.binded=true)},100)}})}if(!s_session.userTips.settingDragTips||self.selected.length==0){self.dialog.body.find(".drag-tips").css("display","none")}self.dialog.show();self.beforeShow();if($.isIE6){$(".sui-dialog-cardsetting .sui-dialog-body").show()}else{if(true){$(".sui-dialog-cardsetting .sui-dialog-body").css({display:"block"});$(".sui-dialog-cardsetting").animate({height:"186px"},200)}else{}}ctx.fire("showSet")}self.dialog.hasshow=true;$(".sui-dialog-body").on("click",function(e
){e.stopPropagation()});self.dialog.body.on("mousedown",function(e){e.stopPropagation()});F.use("common/user_attr",function(e){e.setAttr("settingDragTips",false)})},hide:function(){var self=this;if(self.isShow()){if($.isIE6){$(".sui-dialog-cardsetting .sui-dialog-body").hide();self.dialog.hide()}else{$(".sui-dialog-cardsetting").animate({height:"0px"},200,function(){$(".sui-dialog-cardsetting .sui-dialog-body").css({display:"none"});self.dialog.hide()})}}},isShow:function(){if($(
".sui-dialog-cardsetting .sui-dialog-body").length==0||$(".sui-dialog-cardsetting .sui-dialog-body").css("display")=="none"){return false}else{return true}},beforeShow:function(){var self=this,topWrapper=$("#s_top_wrap"),settingNode=$(".sui-dialog-cardsetting");if(topWrapper.find("#s_menu_gurd").length>0){if($.isIE6){settingNode.css("position","absolute");settingNode.css("top",$(window).scrollTop()-$("#s_main").offset().top+110+"px")}else{settingNode.css("position","fixed");settingNode.css("top"
,"110px");settingNode.css("left",$("#s_main").offset().left)}}else{settingNode.css("position","absolute");settingNode.css("top","36px")}},resort:function(){var cache=this.draggselect.selected.cache;var musicPosition=parseInt($(".s-cardsetting-left .s-mod-music:last").attr("data-daraggsort"),10);if(!isNaN(musicPosition)){var position;for(var index=0,length=cache.length;index<length;index++){if(musicPosition===cache[index]&&index!==0){cache.splice(index,1);cache.unshift(musicPosition)
;this.draggselect.selected.sort(false,true);break}}}},getModIds:function(ids){var ids=ids;if(musicId!==undefined&&!($.inArray(ids,musicId)>-1)){ids.unshift(musicId)}return ids.join(",")}};return new(F.inherit(Cardsetting,Emitter))});
F.module("mancard:subscribe/parabola",function(require,exports,ctx){(function(){var lastTime=0;var vendors=["webkit","moz"];for(var x=0;x<vendors.length&&!window.requestAnimationFrame;++x){window.requestAnimationFrame=window[vendors[x]+"RequestAnimationFrame"];window.cancelAnimationFrame=window[vendors[x]+"CancelAnimationFrame"]||window[vendors[x]+"CancelRequestAnimationFrame"]}if(!window.requestAnimationFrame){window.requestAnimationFrame=function(callback,element){var currTime=(new Date
).getTime();var timeToCall=Math.max(0,16.7-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall)},timeToCall);lastTime=currTime+timeToCall;return id}}if(!window.cancelAnimationFrame){window.cancelAnimationFrame=function(id){clearTimeout(id)}}})();var defaults={speed:166.67,curvature:.001,progress:function(){},complete:function(){callback&&callback()}};var element,target,callback;var params={},options=options||{};for(var key in defaults){
params[key]=options[key]||defaults[key]}exports={mark:function(){return this},position:function(){return this},move:function(){return this},init:function(){return this}};var moveStyle="margin",testDiv=document.createElement("div");if("oninput"in testDiv){["","ms","webkit"].forEach(function(prefix){var transform=prefix+(prefix?"T":"t")+"ransform";if(transform in testDiv.style){moveStyle=transform}})}var a=params.curvature,b=0,c=0;var flagMove=true;var rectElement={},rectTarget={}
;var centerElement={},centerTarget={};var coordElement={},coordTarget={};exports.mark=function(){if(flagMove==false)return this;if(typeof coordElement.x=="undefined")this.position();element.setAttribute("data-center",[coordElement.x,coordElement.y].join());target.setAttribute("data-center",[coordTarget.x,coordTarget.y].join());return this};exports.position=function(){if(flagMove==false)return this;var scrollLeft=document.documentElement.scrollLeft||document.body.scrollLeft,
scrollTop=document.documentElement.scrollTop||document.body.scrollTop;if(moveStyle=="margin"){element.style.marginLeft=element.style.marginTop="0px"}else{element.style[moveStyle]="translate(0, 0)"}rectElement=element.getBoundingClientRect();rectTarget=target.getBoundingClientRect();centerElement={x:rectElement.left+(rectElement.right-rectElement.left)/2+scrollLeft,y:rectElement.top+(rectElement.bottom-rectElement.top)/2+scrollTop};centerTarget={x:rectTarget.left+(rectTarget.right-rectTarget.left
)/2+scrollLeft,y:rectTarget.top+(rectTarget.bottom-rectTarget.top)/2+scrollTop};coordElement={x:0,y:0};coordTarget={x:-1*(centerElement.x-centerTarget.x),y:-1*(centerElement.y-centerTarget.y)};b=(coordTarget.y-a*coordTarget.x*coordTarget.x)/coordTarget.x;return this};exports.move=function(){if(flagMove==false)return this;var startx=0,rate=coordTarget.x>0?1:-1;var step=function(){var tangent=2*a*startx+b;startx=startx+rate*Math.sqrt(params.speed/(tangent*tangent+1));if(
rate==1&&startx>coordTarget.x||rate==-1&&startx<coordTarget.x){startx=coordTarget.x}var x=startx,y=a*x*x+b*x;element.setAttribute("data-center",[Math.round(x),Math.round(y)].join());if(moveStyle=="margin"){element.style.marginLeft=x+"px";element.style.marginTop=y+"px"}else{element.style[moveStyle]="translate("+[x+"px",y+"px"].join()+")"}if(startx!==coordTarget.x){params.progress(x,y);window.requestAnimationFrame(step)}else{params.complete();flagMove=true}};window.requestAnimationFrame(step)
;flagMove=false;return this};exports.init=function(el,tar,cb){element=el;target=tar;callback=cb;this.position().mark().move()};return exports});
